spring:
  profiles:
    active: dev
    
---
server:
  port: 7001
      
#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-dev

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示是否向eurke注册中注册自己
    fetch-registry: false   #表示自己为注册中心
    service-url:
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/



---    
server:
  port: 7001
      
#spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-test

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示是否向eurke注册中注册自己
    fetch-registry: false   #表示自己为注册中心
    service-url:
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    


