server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  #连接到github或gitee
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouxiyao/springcloud-kuang2-config.git #这是https的，不是ssh


#通过 config-server 可以连接到git,访问其中的资源以及配置