server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false #表示是否向eurke注册中注册自己
    fetch-registry: false   #表示自己为注册中心
    service-url:
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/




